#!/bin/bash
: '
# PURPOSE

This script marshals local training of the object detection model. It can be used
to train the model incrementally, using checkpoints.

# USAGE

./train

# NOTES

CPU training is used, not GPU, due to a lack of access.

Training object detection models is very slow. So far: 1250 steps has taken ~10 hours.

The NUM_TRAIN_STEPS parameter must be modified in this file to determine
how many training steps to run for. If you have done any training, the model
will start from the last checkpoint and continue to the new number of steps.

For example, if you first ran this file with NUM_TRAIN_STEPS=100, the model
would train to step 100 and produce a model checkpoint. If you then modify the
parameter to 200 and run again, then tensorflow will pick up the checkpoint at
100 and train to 200 steps. This could be an arg to this file but it is easier
to keep track of by changing the variable.
'

PIPELINE_CONFIG_PATH="models/model/sketchup.config"
MODEL_DIR="models/model"
NUM_TRAIN_STEPS=5
SAMPLE_1_OF_N_EVAL_EXAMPLES=1

export PYTHONPATH=$PYTHONPATH:`pwd`/..:`pwd`/../slim

echo "Training: `date`"

pipenv run python ../object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr \
    &> log/train.log

echo "Training complete (details in log/train.log): `date`"

